[GetWeather]
enable = true
command-format = """⚙️获取天气：
天气 城市名
天气城市名
城市名天气
城市名 天气"""
api-key = """-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIHH0kbBmRxpBLwKQwVZIszIbEBuvGdQHXxuT+0jViEwk
-----END PRIVATE KEY-----"""
api-host = "https://ky5n8ka83w.re.qweatherapi.com"
jwt-kid = "KBB6BKVM5T"  # 从控制台获取的凭据ID
jwt-sub = "2NTGFT493T"  # 从控制台获取的项目ID

# 申请链接： https://dev.qweather.com/ 